fix: replace matplotlib.get_cmap (#1186)
matplotlib 3.11.0
[released](https://github.com/matplotlib/matplotlib/releases/tag/v3.11.0)
yesterday and integration tests are failing now, because 'cm.get_cmap'
has been removed.
[nightly-integration-tests-hpc-gpu ·
ecmwf/anemoi-core@8521cd5](https://github.com/ecmwf/anemoi-core/actions/runs/27403412348/job/80986594455#step:3:2420)
 
 ```
Python
AttributeError: module 'matplotlib.cm' has no attribute 'get_cmap'
Traceback (most recent call last):
File
"/dev/shm/_tmpdir_.***.35537584/anemoi-core/training/src/anemoi/training/diagnostics/callbacks/plot.py",
line 95, in _run
    fn(trainer, *args, **kwargs)
File
"/dev/shm/_tmpdir_.***.35537584/anemoi-core/.venv/lib/python3.12/site-packages/lightning_utilities/core/rank_zero.py",
line 42, in wrapped_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
File
"/dev/shm/_tmpdir_.***.35537584/anemoi-core/training/src/anemoi/training/diagnostics/callbacks/plot.py",
line 1127, in _plot
    fig = self._make_figure(
          ^^^^^^^^^^^^^^^^^^
File
"/dev/shm/_tmpdir_.***.35537584/anemoi-core/training/src/anemoi/training/diagnostics/callbacks/plot.py",
line 1255, in _make_figure
    return plot_predicted_ensemble(
           ^^^^^^^^^^^^^^^^^^^^^^^^
File
"/dev/shm/_tmpdir_.***.35537584/anemoi-core/training/src/anemoi/training/diagnostics/plots.py",
line 1271, in plot_predicted_ensemble
cmap, error_cmap = _resolve_variable_colormaps(colormaps, variable_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File
"/dev/shm/_tmpdir_.***.35537584/anemoi-core/training/src/anemoi/training/diagnostics/plots.py",
line 545, in _resolve_variable_colormaps
cmap = colormaps.default.get_cmap() if colormaps.get("default") else
cm.get_cmap("viridis")
^^^^^^^^^^^
AttributeError: module 'matplotlib.cm' has no attribute 'get_cmap'
```