fix: support pyg-lib for fast graph building when using pyg >= 2.8 (#1179)
## Description
pytorch geometric 2.8 deprecated the torch-cluster library, in favour of
pyg-lib. the api is the same, we just need to change how the library is
checked.

Currently it checks for torch-cluster if PyG <= 2.7.0 and pyg-lib if PyG
>= 2.8.0. This is in order to support multiple versions of PyG, because
PyG 2.8 only supports a limited range of PyTorch versions
(2.9,2.10,2.11,2.12).


if you try import torch-cluster when using PyG 2.8 you get the following
error. This PR fixes this by using pyg-lib instead
```
  File "/perm/naco/venvs/triton-flash-attn/lib/python3.12/site-packages/anemoi/graphs/create.py", line 69, in update_graph
    graph = edge_builder.update_graph(graph, attrs_config=None)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/perm/naco/venvs/triton-flash-attn/lib/python3.12/site-packages/anemoi/graphs/edges/builders/base.py", line 141, in update_graph
    graph = self.register_edges(graph)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/perm/naco/venvs/triton-flash-attn/lib/python3.12/site-packages/anemoi/graphs/edges/builders/base.py", line 87, in register_edges
    edge_index = self.get_edge_index(graph)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/perm/naco/venvs/triton-flash-attn/lib/python3.12/site-packages/anemoi/graphs/edges/builders/base.py", line 71, in get_edge_index
    edge_index = self.compute_edge_index(source_nodes, target_nodes)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/perm/naco/venvs/triton-flash-attn/lib/python3.12/site-packages/anemoi/graphs/edges/builders/cutoff.py", line 242, in compute_edge_index
    return super().compute_edge_index(source_nodes=source_nodes, target_nodes=target_nodes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/perm/naco/venvs/triton-flash-attn/lib/python3.12/site-packages/anemoi/graphs/edges/builders/base.py", line 181, in compute_edge_index
    edge_index = self._compute_edge_index_pyg(source_coords, target_coords)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/perm/naco/venvs/triton-flash-attn/lib/python3.12/site-packages/anemoi/graphs/edges/builders/cutoff.py", line 159, in _compute_edge_index_pyg
    edge_index = radius(source_coords, target_coords, r=self.radius, max_num_neighbors=self.max_num_neighbours)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/perm/naco/venvs/triton-flash-attn/lib/python3.12/site-packages/torch_geometric/nn/pool/__init__.py", line 261, in radius
    raise ImportError("'radius' requires 'pyg-lib>=0.6.0'")
ImportError: 'radius' requires 'pyg-lib>=0.6.0'
```

---------