feat: Deprecate LongRolloutPlots (#1020)
## Description
As mentioned in the issue, this PR of the callbacks refactor. Plot Audit
indicated LongRolloutPlots were not used and they are not being properly
tested or checked as part of the integration tests. We propose to
deprecate them. This PR removes any references and code associated to
them, and includes a proper error catching so that if users try to run
with any configs that specify this callback the code will return:

```
pydantic_core._pydantic_core.ValidationError: 1 validation error for UnvalidatedBaseSchema
  Value error, 'anemoi.training.diagnostics.callbacks.plot.LongRolloutPlots' is deprecated and has been removed. This callback has been deprecated and removed, update your config to remove any references to it.  [type=value_error, input_value={'data': {'format': 'zarr...nfig_validation': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/value_error
```


## What problem does this change solve?
https://github.com/ecmwf/anemoi-core/issues/1019

## What issue or task does this change relate to?
https://github.com/ecmwf/anemoi-core/issues/1019

##  Additional notes ##
<!-- Include any additional information, caveats, or considerations that
the reviewer should be aware of. -->

***As a contributor to the Anemoi framework, please ensure that your
changes include unit tests, updates to any affected dependencies and
documentation, and have been tested in a parallel setting (i.e., with
multiple GPUs). As a reviewer, you are also responsible for verifying
these aspects and requesting changes if they are not adequately
addressed. For guidelines about those please refer to
https://anemoi.readthedocs.io/en/latest/***

By opening this pull request, I affirm that all authors agree to the
[Contributor License
Agreement.](https://github.com/ecmwf/codex/blob/main/Legal/contributor_license_agreement.md)


<!-- readthedocs-preview anemoi-training start -->
----
📚 Documentation preview 📚:
https://anemoi-training--1020.org.readthedocs.build/en/1020/

<!-- readthedocs-preview anemoi-training end -->

<!-- readthedocs-preview anemoi-graphs start -->
----
📚 Documentation preview 📚:
https://anemoi-graphs--1020.org.readthedocs.build/en/1020/

<!-- readthedocs-preview anemoi-graphs end -->

<!-- readthedocs-preview anemoi-models start -->
----
📚 Documentation preview 📚:
https://anemoi-models--1020.org.readthedocs.build/en/1020/

<!-- readthedocs-preview anemoi-models end -->